# -*- coding: utf-8 -*-
"""modules and execption

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OJd8_vBs1H8S2Rxyxdj7B4BAG20dZdf
"""

import math

math.sqrt(1234567890)

import random

random.randint(0,100)

#code to generate the randon number from seleted range

from math import *

sqrt(88)

floor(33)

import langchain

import bs4

#execption handling
1/1

#execption #error
#if pyhton knows what is causing an error its called as execption.
#rest all error which are unknown to python are called as error

print(a_not_defined_variable)

if 573:
  print("hello Sandesh")

#exeception handling

def div_by_zero(x):
  return x/0
div_by_zero(5)
print("hello")

#try and except block
def div_by_zero(a,b):
  return a/b
try:
  div_by_zero(10,2)
except:
  print("error")

l1 = [2, 0, "hello", None]
for e in l1:
  try:
    print (f"Current element - {e}")
    result = 5 / int(e)
    print (f"Result - {result}")
  except Exception as exp:
    print (f"Excpetion - {exp}")
  print ("-"*50)
print ("Execution completed")

try:
  print("i am tring")
  print(1/2)
except:
    print("a")
print("b")

#raising custom execption
raise Exception ("This password is incorrect!")

try:
    assert False, "Error occurred!"
except AssertionError as e:
    print(e)

l1 = [2, 0]

for e in l1:
    try:
        result = 5 / int(e)
        print("N")
    except ZeroDivisionError as z:
        print("Z")

try:
  assert False,'error ocrd'
except assertionError as e:
  print(e)

n=101
a=2
n*a+n*(n-1)

#time complexity
#big o notation
def fun(n,m):
  s=0
  for i in range(1,n+1):
    s=s+i
  for j in range(1,m+1):
    s=s+j
  return s

def fun(n):
  s=0
  for i in range(1,int(n**0.5)):
    s=s+i
  return s

def example_function(arr):
    total = 0
    for i in range(len(arr)):
        for j in range(i + 1, len(arr)):
          k = 1
          while k <= len(arr):
            total += i + j + k
            k *= 2
    return total

try:
  print(a)
except ValueError:
  a=3
  print(a)
except:
  a=5
  print(a)
finally:
  a=4
  print(a)